botniabladet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('upload.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path

from .views import HomePageView, CreatePostView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('post/', CreatePostView.as_view(), name='add_post'),
]

upload/models.py
from django.db import models

# Create your models here.

class Photo(models.Model):
    title = models.TextField()
    image = models.ImageField(upload_to = 'images/')
    uploader_id = models.IntegerField(blank=True, null=True)
    upload_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

upload/forms.py
from django import forms
from .models import Photo

class PhotoUploadForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['title', 'image']

upload/views.py
from django.shortcuts import render

from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy

from .forms import PhotoUploadForm
from .models import Photo


class HomePageView(ListView):
    model = Photo
    template_name = 'home.html'


class CreatePostView(CreateView):
    model = Photo
    form_class = PhotoUploadForm
    template_name = 'upload.html'
    success_url = reverse_lazy('home')

templates/home.html
<h1>Django Image Uploading</h1>
<ul>
  {% for post in object_list %}
    <h2>{{ post.title }}</h2>
    <img src="{{ post.image.url }}" alt="{{ post.title }}">
  {% endfor %}
</ul>

templates/upload.html
<!-- templates/post.html -->
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<title>Botniabladet</title>		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
		{% load static %}
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		
		<!-- JS funktionalitet som är kopplat med Bootstrap -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</head>
  
 	<body>
 		<!-- NAVBAR -->
		<div class="navbar debug">
			<a class="navbar-brand" href="#">Botniabladet</a>
			<div class="row mr">
				<p>Inloggad som fNamn eNamn</p>
				<div class="col-md">
					<button class="btn btn-danger" type="button" name="button">Logga ut</button>
				</div>
			</div>
		</div>
	
		<!-- MAIN CONTENT -->
	    <div class="container center">
		
			<div class="container center">
				<img class="center" height="50%" width="50%" src="https://cdn1.iconfinder.com/data/icons/image-manipulations/100/13-512.png" alt="Ladda upp bilden här">
			</div>
			
			<!-- FORM -->
			<div class="container center debug">
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="col-lg-12">
						<input type="file" name="image" accept="image/*" required id="id_image" class="upload-button">
					</div>

					<!-- LÄGG TILL KATEGORI / LÄGG TILL TAGG -->
					<!-- ** Behöver skrivas om för att hanteras med django ** -->
					<div class="container">
						<div class="row">
							<div class="col-lg-6">
								<button type="button" class="btn btn-primary" name="button">Lägg till Kategori</button>
								<p>Kategori</p>
								<p>Underkategori</p>
							</div>
							<div class="col-lg-6">
								<button type="button" class="btn btn-primary" name="button">Lägg till Taggar</button>
								<p><a href="#"><u>#tagname</u></a></p>
								<p><a href="#"><u>#tagname</u></a></p>
								<p><a href="#"><u>#tagname</u></a></p>
							</div>
						</div>
					</div>
					
					<input type="text" name="title" value="Test" class="vTextField" maxlength="24" required="" id="id_title">
					<button type="submit" class="btn btn-primary">Ladda upp</button>
				</form>
			</div>

	    </div>
  	</body>
</html>